import { useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { CalendarDays, Download, Search, Users } from "lucide-react";
import { api } from "../api/Client";

const iso = (date) => date.toISOString().slice(0, 10);
const fmtDuration = (seconds = 0) => `${Math.floor(seconds / 3600)}h ${String(Math.floor(seconds % 3600 / 60)).padStart(2, "0")}m`;
const fmtTime = (value) => value ? new Date(value).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }) : "—";
const today = new Date(); const monthStart = new Date(today.getFullYear(), today.getMonth(), 1);

export default function AdminAttendanceHistory() {
  const [employees, setEmployees] = useState([]), [employeeId, setEmployeeId] = useState(""), [detail, setDetail] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [from, setFrom] = useState(iso(monthStart)), [to, setTo] = useState(iso(today)), [query, setQuery] = useState("");
  useEffect(() => { api.get("/admin/employees").then(({ data }) => { setEmployees(data.employees); if (data.employees[0]) setEmployeeId(data.employees[0].id); }).catch(() => setError("Unable to load employees.")).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!employeeId) return; setLoading(true); setError(""); api.get(`/admin/employees/${employeeId}/attendance`, { params: { from, to } }).then(({ data }) => setDetail(data)).catch((e) => setError(e.response?.data?.error || "Unable to load attendance history.")).finally(() => setLoading(false)); }, [employeeId, from, to]);
  const displayed = useMemo(() => employees.filter((employee) => `${employee.firstName} ${employee.lastName} ${employee.email}`.toLowerCase().includes(query.toLowerCase())), [employees, query]);
  const exportExcel = () => {
    if (!detail) return;
    const rows = detail.records.flatMap((record) => record.logs?.length ? record.logs.map((log) => ({ Date: record.date, Status: record.statusLabel, Late: record.isLate ? "Yes" : "No", "Punch event": log.type === "punch_in" ? "Punch In" : "Punch Out", Time: fmtTime(log.at), "Daily worked time": fmtDuration(record.totalWorkedSeconds) })) : [{ Date: record.date, Status: record.statusLabel, Late: record.isLate ? "Yes" : "No", "Punch event": "No punches", Time: "—", "Daily worked time": fmtDuration(record.totalWorkedSeconds) }]);
    rows.unshift({ Date: `Employee: ${detail.employee.firstName} ${detail.employee.lastName}`, Status: `Range: ${from} to ${to}` });
    const sheet = XLSX.utils.json_to_sheet(rows); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, sheet, "Attendance History"); XLSX.writeFile(workbook, `${detail.employee.firstName}-${detail.employee.lastName}-attendance-${from}-${to}.xlsx`);
  };
  return <div className="mx-auto max-w-7xl p-2 font-sans sm:p-5"><header className="mb-6"><h1 className="text-2xl font-semibold text-slate-900">Employee attendance history</h1><p className="mt-1 text-sm text-slate-500">Review attendance, every punch event, total hours, and export the selected employee’s history.</p></header>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 xl:flex-row xl:items-end xl:gap-2"><div className="min-w-0 xl:w-[390px]"><label className="text-xs font-semibold uppercase tracking-wide text-slate-400">Employee</label><div className="mt-1 flex gap-2"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={15}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-amber-400 focus:ring-2 focus:ring-amber-100"/></div><select value={employeeId} onChange={(e) => setEmployeeId(e.target.value)} className="w-[220px] rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-amber-400 focus:ring-2 focus:ring-amber-100">{displayed.map((employee) => <option value={employee.id} key={employee.id}>{employee.firstName} {employee.lastName}</option>)}</select></div></div><label className="xl:w-[155px] text-xs font-semibold uppercase tracking-wide text-slate-400">From<input type="date" value={from} max={to} onChange={(e) => setFrom(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-amber-400 focus:ring-2 focus:ring-amber-100"/></label><label className="xl:w-[155px] text-xs font-semibold uppercase tracking-wide text-slate-400">To<input type="date" value={to} min={from} max={iso(today)} onChange={(e) => setTo(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-amber-400 focus:ring-2 focus:ring-amber-100"/></label><button disabled={!detail} onClick={exportExcel} className="flex h-[42px] shrink-0 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-semibold text-white shadow-sm transition hover:bg-emerald-700 disabled:opacity-50"><Download size={16}/>Export Excel</button></div></section>
    {error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    {loading && <p className="mt-6 text-sm text-slate-500">Loading attendance history...</p>}
    {detail && !loading && <><section className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-5"><Metric label="Present" value={detail.summary.present}/><Metric label="Half Day" value={detail.summary.halfDay}/><Metric label="Absent" value={detail.summary.absent}/><Metric label="Late" value={detail.summary.late}/><Metric label="Worked time" value={fmtDuration(detail.summary.totalWorkedSeconds)}/></section><section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><div className="rounded-xl bg-slate-100 p-2 text-slate-600"><Users size={18}/></div><div><h2 className="font-semibold text-slate-900">{detail.employee.firstName} {detail.employee.lastName}</h2><p className="text-xs text-slate-500">{detail.employee.department} · {detail.summary.attendanceRate}% attendance rate</p></div></div>{detail.records.length === 0 ? <div className="p-12 text-center text-sm text-slate-400">No attendance records in this date range.</div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Date</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Punches</th><th className="px-3 py-3">Worked</th><th className="px-5 py-3">Audit log</th></tr></thead><tbody>{detail.records.map((record) => <tr key={record._id} className="border-t border-slate-100 align-top"><td className="px-5 py-4 font-medium text-slate-700">{record.date}</td><td className="px-3 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700">{record.statusLabel}{record.isLate ? " · Late" : ""}</span></td><td className="px-3 py-4 text-slate-600">{record.sessions?.map((session) => `${fmtTime(session.punchIn)} – ${fmtTime(session.punchOut)}`).join(" | ") || "—"}</td><td className="px-3 py-4 font-mono text-slate-700">{fmtDuration(record.totalWorkedSeconds)}</td><td className="px-5 py-4 text-xs text-slate-500">{record.logs?.map((log) => `${log.type === "punch_in" ? "In" : "Out"}: ${fmtTime(log.at)}`).join(" · ")}</td></tr>)}</tbody></table></div>}</section></>}</div>;
}
function Metric({ label, value }) { return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-lg font-semibold text-slate-900">{value}</p><p className="mt-1 text-[11px] font-medium uppercase tracking-wide text-slate-400">{label}</p></div>; }
