import { useEffect, useState } from "react";
import { Save, Settings2 } from "lucide-react";
import { api } from "../api/Client";

const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export default function AttendanceConfiguration() {
  const [config, setConfig] = useState(null), [saved, setSaved] = useState(null), [message, setMessage] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { api.get("/admin/attendance-config").then(({ data }) => { setConfig(data.config); setSaved(JSON.stringify(data.config)); }).catch(() => setError("Unable to load attendance configuration.")); }, []);
  if (!config) return <div className="p-6 text-sm text-slate-500">Loading attendance configuration...</div>;
  const change = (key, value) => { setConfig((current) => ({ ...current, [key]: value })); setMessage(""); };
  const isDirty = JSON.stringify(config) !== saved;
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const { data } = await api.put("/admin/attendance-config", config); setConfig(data.config); setSaved(JSON.stringify(data.config)); setMessage(data.message); } catch (e) { setError(e.response?.data?.error || "Unable to save attendance configuration."); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-4xl p-2 font-sans sm:p-5"><div className="mb-6 flex items-start gap-3"><div className="rounded-xl bg-amber-100 p-3 text-amber-700"><Settings2 size={22}/></div><div><h1 className="text-2xl font-semibold text-slate-900">Attendance configuration</h1><p className="mt-1 text-sm text-slate-500">Changes apply to future punch-ins only; existing attendance remains audited.</p></div></div>
    <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-7">
      <label className="text-sm font-medium text-slate-700">Timezone<select value={config.timezone} onChange={(e) => change("timezone", e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3"><option value="Asia/Kolkata">Asia/Kolkata</option><option value="UTC">UTC</option><option value="Asia/Dubai">Asia/Dubai</option><option value="Europe/London">Europe/London</option><option value="America/New_York">America/New_York</option></select></label>
      <label className="text-sm font-medium text-slate-700">Attendance mode<select value={config.attendanceMode} onChange={(e) => change("attendanceMode", e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3"><option value="multiple_sessions">Multiple sessions</option><option value="single_session">Single session</option></select></label>
      <label className="text-sm font-medium text-slate-700">Punch-in availability<select value={config.punchInRestriction || "anytime"} onChange={(e) => change("punchInRestriction", e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3"><option value="anytime">Any time during the day</option><option value="shift_hours">Only during assigned daytime shift hours</option></select><span className="mt-1 block text-xs font-normal text-slate-400">Shift-only mode accepts only same-day shifts, for example 09:00–18:00.</span></label>
      <label className="text-sm font-medium text-slate-700">Default shift start<input type="time" value={config.defaultShiftStart} onChange={(e) => change("defaultShiftStart", e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3" /></label>
      <label className="text-sm font-medium text-slate-700">Default shift end<input type="time" value={config.defaultShiftEnd} onChange={(e) => change("defaultShiftEnd", e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3" /></label>
      <label className="text-sm font-medium text-slate-700">Late grace (minutes)<input type="number" min="0" max="240" value={config.lateGraceMinutes} onChange={(e) => change("lateGraceMinutes", Number(e.target.value))} className="mt-2 w-full rounded-xl border border-slate-200 p-3" /></label>
      <label className="text-sm font-medium text-slate-700">Half-day minimum hours<input type="number" step="0.25" min="0.25" value={config.halfDayHours} onChange={(e) => change("halfDayHours", Number(e.target.value))} className="mt-2 w-full rounded-xl border border-slate-200 p-3" /></label>
      <label className="text-sm font-medium text-slate-700">Full-day minimum hours<input type="number" step="0.25" min="0.5" value={config.fullDayHours} onChange={(e) => change("fullDayHours", Number(e.target.value))} className="mt-2 w-full rounded-xl border border-slate-200 p-3" /></label>
      <div className="text-sm font-medium text-slate-700"><p>Working days</p><div className="mt-2 flex flex-wrap gap-2">{DAYS.map((day, index) => <button type="button" onClick={() => change("workingDays", config.workingDays.includes(index) ? config.workingDays.filter((value) => value !== index) : [...config.workingDays, index])} className={`rounded-lg px-3 py-2 text-xs font-semibold ${config.workingDays.includes(index) ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-600"}`} key={day}>{day}</button>)}</div></div>
    </div><div className="flex items-center justify-between border-t border-slate-100 p-5"><p className={`text-sm ${error ? "text-rose-600" : "text-emerald-600"}`}>{error || message || (isDirty ? "Unsaved changes" : "")}</p><button disabled={!isDirty || saving} className="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save size={16}/>{saving ? "Saving..." : "Save configuration"}</button></div></form></div>;
}
