import { Router } from "express";
import { Attendance } from "../models/attendance.model.js";
import { Organization } from "../models/organization.model.js";
import { auth } from "../middleware/auth.js";
import { dateInTimezone, isWithinShiftHours, localMinutes, minutesForTime, policyFor, publicStatus, statusForSeconds } from "../src/utils/attendance.js";

const router = Router();
router.use(auth);
async function context(req) { const organization = await Organization.findById(req.user.organization).lean(); return { organization, policy: policyFor(organization), now: new Date() }; }
const serialize = (record, policy) => ({ ...(record?.toObject?.() || record || {}), date: record?.date || dateInTimezone(new Date(), policy.timezone), statusLabel: publicStatus(record), policy: record?.policySnapshot || policy });

router.get("/summary", async (req, res, next) => {
  try {
    const { policy, now } = await context(req); const today = dateInTimezone(now, policy.timezone); const start = new Date(now); start.setDate(start.getDate() - 29);
    const records = await Attendance.find({ user: req.user._id, date: { $gte: dateInTimezone(start, policy.timezone), $lte: today } }).sort({ date: 1 }).lean(); const byDate = new Map(records.map((r) => [r.date, r]));
    const week = Array.from({ length: 7 }, (_, i) => { const d = new Date(now); d.setDate(now.getDate() - ((now.getDay() + 6) % 7) + i); const key = dateInTimezone(d, policy.timezone); return { day: d.toLocaleDateString("en-US", { weekday: "short", timeZone: policy.timezone }), hours: (byDate.get(key)?.totalWorkedSeconds || 0) / 3600 }; });
    const completed = records.filter((r) => r.status === "completed"), attended = completed.filter((r) => r.attendanceStatus !== "absent"), checkIns = records.filter((r) => r.firstPunchIn).map((r) => new Date(r.firstPunchIn));
    res.json({ summary: { week, weekTotalHours: week.reduce((sum, item) => sum + item.hours, 0), attendanceRate: completed.length ? attended.length / completed.length * 100 : 0, averageCheckInMinutes: checkIns.length ? checkIns.reduce((sum, d) => sum + localMinutes(d, policy.timezone), 0) / checkIns.length : null, today: serialize(byDate.get(today), policy), policy } });
  } catch (error) { next(error); }
});
router.get("/today", async (req, res, next) => { try { const { policy, now } = await context(req); const record = await Attendance.findOne({ user: req.user._id, date: dateInTimezone(now, policy.timezone) }); res.json({ attendance: serialize(record, policy), policy }); } catch (error) { next(error); } });
router.post("/punch-in", async (req, res, next) => {
  try { const { organization, policy, now } = await context(req); const date = dateInTimezone(now, policy.timezone); let record = await Attendance.findOne({ user: req.user._id, date }); if (record?.status === "working") return res.status(409).json({ error: "You are already punched in" }); if (!record) record = new Attendance({ organization: organization._id, user: req.user._id, date, policySnapshot: policy }); const snapshot = record.policySnapshot || policy; const shiftStart = req.user.shiftStart || snapshot.defaultShiftStart, shiftEnd = req.user.shiftEnd || snapshot.defaultShiftEnd; if (snapshot.punchInRestriction === "shift_hours" && !isWithinShiftHours(now, snapshot.timezone, shiftStart, shiftEnd)) return res.status(403).json({ error: `Punch in is allowed only during your shift (${shiftStart}–${shiftEnd}).` }); if (snapshot.attendanceMode === "single_session" && record.sessions.length) return res.status(409).json({ error: "Only one attendance session is allowed today" }); record.status = "working"; record.attendanceStatus = "in_progress"; record.firstPunchIn ||= now; record.isLate ||= localMinutes(now, snapshot.timezone) > minutesForTime(shiftStart) + snapshot.lateGraceMinutes; record.sessions.push({ punchIn: now }); record.logs.push({ type: "punch_in", at: now }); await record.save(); res.status(201).json({ attendance: serialize(record, snapshot) }); } catch (error) { next(error); }
});
async function punchOutPreview(req) { const { policy, now } = await context(req); const record = await Attendance.findOne({ user: req.user._id, date: dateInTimezone(now, policy.timezone) }); if (!record || record.status !== "working") return { error: "You are not punched in" }; const projectedSeconds = record.totalWorkedSeconds + Math.max(0, Math.floor((now - record.sessions.at(-1).punchIn) / 1000)); const snapshot = record.policySnapshot || policy; return { record, now, snapshot, projectedSeconds, attendanceStatus: statusForSeconds(projectedSeconds, snapshot) }; }
router.post("/punch-out/preview", async (req, res, next) => { try { const result = await punchOutPreview(req); if (result.error) return res.status(409).json({ error: result.error }); res.json({ projectedSeconds: result.projectedSeconds, status: publicStatus({ status: "completed", attendanceStatus: result.attendanceStatus }), halfDaySeconds: result.snapshot.halfDayHours * 3600, fullDaySeconds: result.snapshot.fullDayHours * 3600 }); } catch (error) { next(error); } });
router.post("/punch-out", async (req, res, next) => { try { const result = await punchOutPreview(req); if (result.error) return res.status(409).json({ error: result.error }); const { record, now, snapshot, projectedSeconds, attendanceStatus } = result; record.sessions.at(-1).punchOut = now; record.totalWorkedSeconds = projectedSeconds; record.lastPunchOut = now; record.logs.push({ type: "punch_out", at: now }); record.status = "completed"; record.attendanceStatus = attendanceStatus; await record.save(); res.json({ attendance: serialize(record, snapshot) }); } catch (error) { next(error); } });
router.get("/history", async (req, res, next) => { try { const { policy } = await context(req); const page = Math.max(1, Number(req.query.page) || 1), limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20)), filter = { user: req.user._id }; if (req.query.from || req.query.to) filter.date = { ...(req.query.from ? { $gte: req.query.from } : {}), ...(req.query.to ? { $lte: req.query.to } : {}) }; const [records, total] = await Promise.all([Attendance.find(filter).sort({ date: -1 }).skip((page - 1) * limit).limit(limit).lean(), Attendance.countDocuments(filter)]); res.json({ records: records.map((r) => serialize(r, policy)), page, limit, total, pages: Math.ceil(total / limit) }); } catch (error) { next(error); } });
export default router;
